Use Sequence instead of List (#285)
```
pip install lsprotocol
pip install mypy
```

The `main.py`:
```
from typing import List
from lsprotocol import types


def get_edits() -> List[types.TextEdit]:
    return [
        types.TextEdit(
            types.Range(types.Position(0, 0), types.Position(0, 1)),
            'new text'
        )
    ]


edits = get_edits()

types.TextDocumentEdit(
    types.OptionalVersionedTextDocumentIdentifier('file', 1),
    edits,
)
```

The output of `mypy main.py`:
```
main.py:18: error: Argument 2 to "TextDocumentEdit" has incompatible type "list[TextEdit]"; expected "list[TextEdit | AnnotatedTextEdit]"  [arg-type]
main.py:18: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
main.py:18: note: Consider using "Sequence" instead, which is covariant
Found 1 error in 1 file (checked 1 source file)
```

Replacing `List` with `Sequence` solve the error reported by Mypy:
```
Success: no issues found in 1 source file
```